using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class StartOfSimulation : MonoBehaviour {

	// Use this for initialization
	void Start ()
	{
	  
	}
	
	// Update is called once per frame
  void Update()
  {

  }

  void OnEnable()
  {
    //Tell our 'OnLevelFinishedLoading' function to start listening for a scene change as soon as this script is enabled.
    SceneManager.sceneLoaded += OnLevelFinishedLoading;
  }

  void OnDisable()
  {
    //Tell our 'OnLevelFinishedLoading' function to stop listening for a scene change as soon as this script is disabled. Remember to always have an unsubscription for every delegate you subscribe to!
    SceneManager.sceneLoaded -= OnLevelFinishedLoading;
  }

  void OnLevelFinishedLoading(Scene scene, LoadSceneMode mode)
  {
    var sim = Simulation.getInstance();
    sim.Reset();
  }
}
